/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as toolsWordCounterRouteImport } from './routes/(tools)/word-counter'
import { Route as toolsVideoTrimmerRouteImport } from './routes/(tools)/video-trimmer'
import { Route as toolsUuidGeneratorRouteImport } from './routes/(tools)/uuid-generator'
import { Route as toolsUnitConverterRouteImport } from './routes/(tools)/unit-converter'
import { Route as toolsTextCaseConverterRouteImport } from './routes/(tools)/text-case-converter'
import { Route as toolsPasswordGeneratorRouteImport } from './routes/(tools)/password-generator'
import { Route as toolsLoremIpsumRouteImport } from './routes/(tools)/lorem-ipsum'
import { Route as toolsImagePaletteGeneratorRouteImport } from './routes/(tools)/image-palette-generator'
import { Route as toolsImageCropperRouteImport } from './routes/(tools)/image-cropper'
import { Route as toolsImageCompressorRouteImport } from './routes/(tools)/image-compressor'
import { Route as toolsDiffCheckerRouteImport } from './routes/(tools)/diff-checker'
import { Route as toolsColorPickerRouteImport } from './routes/(tools)/color-picker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsWordCounterRoute = toolsWordCounterRouteImport.update({
  id: '/(tools)/word-counter',
  path: '/word-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsVideoTrimmerRoute = toolsVideoTrimmerRouteImport.update({
  id: '/(tools)/video-trimmer',
  path: '/video-trimmer',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsUuidGeneratorRoute = toolsUuidGeneratorRouteImport.update({
  id: '/(tools)/uuid-generator',
  path: '/uuid-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsUnitConverterRoute = toolsUnitConverterRouteImport.update({
  id: '/(tools)/unit-converter',
  path: '/unit-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsTextCaseConverterRoute = toolsTextCaseConverterRouteImport.update({
  id: '/(tools)/text-case-converter',
  path: '/text-case-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsPasswordGeneratorRoute = toolsPasswordGeneratorRouteImport.update({
  id: '/(tools)/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsLoremIpsumRoute = toolsLoremIpsumRouteImport.update({
  id: '/(tools)/lorem-ipsum',
  path: '/lorem-ipsum',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsImagePaletteGeneratorRoute =
  toolsImagePaletteGeneratorRouteImport.update({
    id: '/(tools)/image-palette-generator',
    path: '/image-palette-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const toolsImageCropperRoute = toolsImageCropperRouteImport.update({
  id: '/(tools)/image-cropper',
  path: '/image-cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsImageCompressorRoute = toolsImageCompressorRouteImport.update({
  id: '/(tools)/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsDiffCheckerRoute = toolsDiffCheckerRouteImport.update({
  id: '/(tools)/diff-checker',
  path: '/diff-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const toolsColorPickerRoute = toolsColorPickerRouteImport.update({
  id: '/(tools)/color-picker',
  path: '/color-picker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/color-picker': typeof toolsColorPickerRoute
  '/diff-checker': typeof toolsDiffCheckerRoute
  '/image-compressor': typeof toolsImageCompressorRoute
  '/image-cropper': typeof toolsImageCropperRoute
  '/image-palette-generator': typeof toolsImagePaletteGeneratorRoute
  '/lorem-ipsum': typeof toolsLoremIpsumRoute
  '/password-generator': typeof toolsPasswordGeneratorRoute
  '/text-case-converter': typeof toolsTextCaseConverterRoute
  '/unit-converter': typeof toolsUnitConverterRoute
  '/uuid-generator': typeof toolsUuidGeneratorRoute
  '/video-trimmer': typeof toolsVideoTrimmerRoute
  '/word-counter': typeof toolsWordCounterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/color-picker': typeof toolsColorPickerRoute
  '/diff-checker': typeof toolsDiffCheckerRoute
  '/image-compressor': typeof toolsImageCompressorRoute
  '/image-cropper': typeof toolsImageCropperRoute
  '/image-palette-generator': typeof toolsImagePaletteGeneratorRoute
  '/lorem-ipsum': typeof toolsLoremIpsumRoute
  '/password-generator': typeof toolsPasswordGeneratorRoute
  '/text-case-converter': typeof toolsTextCaseConverterRoute
  '/unit-converter': typeof toolsUnitConverterRoute
  '/uuid-generator': typeof toolsUuidGeneratorRoute
  '/video-trimmer': typeof toolsVideoTrimmerRoute
  '/word-counter': typeof toolsWordCounterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(tools)/color-picker': typeof toolsColorPickerRoute
  '/(tools)/diff-checker': typeof toolsDiffCheckerRoute
  '/(tools)/image-compressor': typeof toolsImageCompressorRoute
  '/(tools)/image-cropper': typeof toolsImageCropperRoute
  '/(tools)/image-palette-generator': typeof toolsImagePaletteGeneratorRoute
  '/(tools)/lorem-ipsum': typeof toolsLoremIpsumRoute
  '/(tools)/password-generator': typeof toolsPasswordGeneratorRoute
  '/(tools)/text-case-converter': typeof toolsTextCaseConverterRoute
  '/(tools)/unit-converter': typeof toolsUnitConverterRoute
  '/(tools)/uuid-generator': typeof toolsUuidGeneratorRoute
  '/(tools)/video-trimmer': typeof toolsVideoTrimmerRoute
  '/(tools)/word-counter': typeof toolsWordCounterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/color-picker'
    | '/diff-checker'
    | '/image-compressor'
    | '/image-cropper'
    | '/image-palette-generator'
    | '/lorem-ipsum'
    | '/password-generator'
    | '/text-case-converter'
    | '/unit-converter'
    | '/uuid-generator'
    | '/video-trimmer'
    | '/word-counter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/color-picker'
    | '/diff-checker'
    | '/image-compressor'
    | '/image-cropper'
    | '/image-palette-generator'
    | '/lorem-ipsum'
    | '/password-generator'
    | '/text-case-converter'
    | '/unit-converter'
    | '/uuid-generator'
    | '/video-trimmer'
    | '/word-counter'
  id:
    | '__root__'
    | '/'
    | '/(tools)/color-picker'
    | '/(tools)/diff-checker'
    | '/(tools)/image-compressor'
    | '/(tools)/image-cropper'
    | '/(tools)/image-palette-generator'
    | '/(tools)/lorem-ipsum'
    | '/(tools)/password-generator'
    | '/(tools)/text-case-converter'
    | '/(tools)/unit-converter'
    | '/(tools)/uuid-generator'
    | '/(tools)/video-trimmer'
    | '/(tools)/word-counter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  toolsColorPickerRoute: typeof toolsColorPickerRoute
  toolsDiffCheckerRoute: typeof toolsDiffCheckerRoute
  toolsImageCompressorRoute: typeof toolsImageCompressorRoute
  toolsImageCropperRoute: typeof toolsImageCropperRoute
  toolsImagePaletteGeneratorRoute: typeof toolsImagePaletteGeneratorRoute
  toolsLoremIpsumRoute: typeof toolsLoremIpsumRoute
  toolsPasswordGeneratorRoute: typeof toolsPasswordGeneratorRoute
  toolsTextCaseConverterRoute: typeof toolsTextCaseConverterRoute
  toolsUnitConverterRoute: typeof toolsUnitConverterRoute
  toolsUuidGeneratorRoute: typeof toolsUuidGeneratorRoute
  toolsVideoTrimmerRoute: typeof toolsVideoTrimmerRoute
  toolsWordCounterRoute: typeof toolsWordCounterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/word-counter': {
      id: '/(tools)/word-counter'
      path: '/word-counter'
      fullPath: '/word-counter'
      preLoaderRoute: typeof toolsWordCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/video-trimmer': {
      id: '/(tools)/video-trimmer'
      path: '/video-trimmer'
      fullPath: '/video-trimmer'
      preLoaderRoute: typeof toolsVideoTrimmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/uuid-generator': {
      id: '/(tools)/uuid-generator'
      path: '/uuid-generator'
      fullPath: '/uuid-generator'
      preLoaderRoute: typeof toolsUuidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/unit-converter': {
      id: '/(tools)/unit-converter'
      path: '/unit-converter'
      fullPath: '/unit-converter'
      preLoaderRoute: typeof toolsUnitConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/text-case-converter': {
      id: '/(tools)/text-case-converter'
      path: '/text-case-converter'
      fullPath: '/text-case-converter'
      preLoaderRoute: typeof toolsTextCaseConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/password-generator': {
      id: '/(tools)/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof toolsPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/lorem-ipsum': {
      id: '/(tools)/lorem-ipsum'
      path: '/lorem-ipsum'
      fullPath: '/lorem-ipsum'
      preLoaderRoute: typeof toolsLoremIpsumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/image-palette-generator': {
      id: '/(tools)/image-palette-generator'
      path: '/image-palette-generator'
      fullPath: '/image-palette-generator'
      preLoaderRoute: typeof toolsImagePaletteGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/image-cropper': {
      id: '/(tools)/image-cropper'
      path: '/image-cropper'
      fullPath: '/image-cropper'
      preLoaderRoute: typeof toolsImageCropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/image-compressor': {
      id: '/(tools)/image-compressor'
      path: '/image-compressor'
      fullPath: '/image-compressor'
      preLoaderRoute: typeof toolsImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/diff-checker': {
      id: '/(tools)/diff-checker'
      path: '/diff-checker'
      fullPath: '/diff-checker'
      preLoaderRoute: typeof toolsDiffCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tools)/color-picker': {
      id: '/(tools)/color-picker'
      path: '/color-picker'
      fullPath: '/color-picker'
      preLoaderRoute: typeof toolsColorPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  toolsColorPickerRoute: toolsColorPickerRoute,
  toolsDiffCheckerRoute: toolsDiffCheckerRoute,
  toolsImageCompressorRoute: toolsImageCompressorRoute,
  toolsImageCropperRoute: toolsImageCropperRoute,
  toolsImagePaletteGeneratorRoute: toolsImagePaletteGeneratorRoute,
  toolsLoremIpsumRoute: toolsLoremIpsumRoute,
  toolsPasswordGeneratorRoute: toolsPasswordGeneratorRoute,
  toolsTextCaseConverterRoute: toolsTextCaseConverterRoute,
  toolsUnitConverterRoute: toolsUnitConverterRoute,
  toolsUuidGeneratorRoute: toolsUuidGeneratorRoute,
  toolsVideoTrimmerRoute: toolsVideoTrimmerRoute,
  toolsWordCounterRoute: toolsWordCounterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
